# fly.toml app configuration file generated for wetube-holy-field-8825 on 2025-01-27T01:55:51+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wetube-holy-field-8825'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
